{% set name = "kaggle" %}
{% set version = "1.6.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3bd2ef2def44266c1c3115cfefb5acb8f9e69064f2cf9f0ca58dfa4bec6d2c1b

build:
  number: 0
  noarch: python
  entry_points:
    - kaggle = kaggle.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - certifi
    - python-dateutil
    - python-slugify
    - requests
    - six >=1.10
    - tqdm
    - urllib3
    - bleach

test:
  commands:
    - export KAGGLE_USERNAME=datadinosaur  # [unix]
    - export KAGGLE_KEY=xxxxxxxxxxxxxx  # [unix]
    - set KAGGLE_USERNAME=datadinosaur  # [win]
    - set KAGGLE_KEY=xxxxxxxxxxxxxx  # [win]
    - kaggle --help

about:
  home: https://github.com/Kaggle/kaggle-api
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Kaggle API
  description: |
    Official API for https://www.kaggle.com, accessible using a command 
    line tool implemented in Python.
  doc_url: https://github.com/Kaggle/kaggle-api
  dev_url: https://github.com/Kaggle/kaggle-api

extra:
  recipe-maintainers:
    - ngam
    - CurtLH
