{% set name = "kaggle" %}
{% set version = "1.7.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d9821bd6a6a1470741c76d26495a18475b5a7bfe0c80b19191254b2735d41dd

build:
  number: 0
  noarch: python
  entry_points:
    - kaggle = kaggle.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - certifi
    - python-dateutil
    - python-slugify
    - requests
    - six >=1.10
    - tqdm
    - urllib3
    - bleach

test:
  requires:
    - python {{ python_min }}
  commands:
    - export KAGGLE_USERNAME=datadinosaur  # [unix]
    - export KAGGLE_KEY=xxxxxxxxxxxxxx  # [unix]
    - set KAGGLE_USERNAME=datadinosaur  # [win]
    - set KAGGLE_KEY=xxxxxxxxxxxxxx  # [win]
    - kaggle --help

about:
  home: https://github.com/Kaggle/kaggle-api
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Kaggle API
  description: |
    Official API for https://www.kaggle.com, accessible using a command 
    line tool implemented in Python.
  doc_url: https://github.com/Kaggle/kaggle-api
  dev_url: https://github.com/Kaggle/kaggle-api

extra:
  recipe-maintainers:
    - ngam
    - CurtLH
