schema_version: 1

context:
  version: 2.2.4

package:
  name: kaggle
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/k/kaggle/kaggle-${{ version }}.tar.gz
  sha256: 28a58f6c1b9f46ce2afdfb439e0c4e91219e818b377ea4254f4e479456d8cb78

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - kaggle = kaggle.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - bleach
    - kagglesdk >=0.1.35,<1.0
    - python-slugify
    - requests
    - python-dateutil
    - tqdm
    - urllib3 >=1.15.1
    - packaging
    - protobuf
    - jupytext
    - python-dotenv

tests:
  - python:
      imports:
        - kaggle
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pytest
    files:
      source:
        - tests/
    script:
      env:
        KAGGLE_USERNAME: datadinosaur
        KAGGLE_KEY: xxxxxxxxxxxxxx
      content:
        - kaggle --help
        - pytest tests/integration tests/unit

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Kaggle API
  description: |
    Official API for https://www.kaggle.com, accessible using a command
    line tool implemented in Python.
  homepage: https://github.com/Kaggle/kaggle-api
  repository: https://github.com/Kaggle/kaggle-api
  documentation: https://github.com/Kaggle/kaggle-api

extra:
  recipe-maintainers:
    - ngam
    - CurtLH
    - synapticarbors
    - mgorny
