schema_version: 1

context:
  name: kaggle
  version: "1.8.2"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: d3945c32ce6f81046592d14f6d233ee1aec92769682fce4b05b3409e086db5f7

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - kaggle = kaggle.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - bleach
    - kagglesdk
    - python-slugify
    - requests
    - setuptools >=21.0.0
    - six >=1.10
    - tqdm
    - urllib3 >=1.15.1
    - protobuf
    - black >=24.10.0
    - mypy >=1.15.0
    - types-requests
    - types-tqdm
    # not listed in pyproject.toml
    - python-dateutil

tests:
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check
      - if: unix
        then:
          - export KAGGLE_USERNAME=datadinosaur
          - export KAGGLE_KEY=xxxxxxxxxxxxxx
      - if: win
        then:
          - set KAGGLE_USERNAME=datadinosaur
          - set KAGGLE_KEY=xxxxxxxxxxxxxx
      - kaggle --help

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Kaggle API
  description: |
    Official API for https://www.kaggle.com, accessible using a command
    line tool implemented in Python.
  homepage: https://github.com/Kaggle/kaggle-api
  repository: https://github.com/Kaggle/kaggle-api
  documentation: https://github.com/Kaggle/kaggle-api

extra:
  recipe-maintainers:
    - ngam
    - CurtLH
    - synapticarbors
